// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv3WkyNRXv2iQbqDfxxcdhW2LQItH7zgo',
    appId: '1:1084946029551:web:dd4de1893b8967c0f6b41a',
    messagingSenderId: '1084946029551',
    projectId: 'pees-98812',
    authDomain: 'pees-98812.firebaseapp.com',
    storageBucket: 'pees-98812.appspot.com',
    measurementId: 'G-BW4TF1M2YZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNEKx50kS58K1prhAVxGqL7ZucPM_yBkk',
    appId: '1:1084946029551:android:1c317e3bda23cf75f6b41a',
    messagingSenderId: '1084946029551',
    projectId: 'pees-98812',
    storageBucket: 'pees-98812.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGJb55dH48MBkI6KcTu5p0CGnnsGjfM-0',
    appId: '1:1084946029551:ios:4fd08737d364f41ef6b41a',
    messagingSenderId: '1084946029551',
    projectId: 'pees-98812',
    storageBucket: 'pees-98812.appspot.com',
    iosClientId: '1084946029551-eqhg8djjmbfvnmugj1obul5142ne1u22.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGJb55dH48MBkI6KcTu5p0CGnnsGjfM-0',
    appId: '1:1084946029551:ios:e3d235d949dc3d6bf6b41a',
    messagingSenderId: '1084946029551',
    projectId: 'pees-98812',
    storageBucket: 'pees-98812.appspot.com',
    iosClientId: '1084946029551-tvfrc9jrsj4dif2l49mhf32e8ovr381v.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
